### ISSUE TITLE
Why the server only accept speech sent at byterate / s

### ISSUE THREAD

**Issue by truongdo** [alumae/kaldi-gstreamer-server#92]
Hi @alumae 

I'm wondering why the server only works well if the audio is sent at byterate / secs.
Let's say we already have an audio and want to decode it as fast as possible, we would have to send it at much higher rate.

**Comment by alumae** [comment]
It should work just as well with audio that is sent at much higher rate.

However, I don't know what happens if you send a very large chunk of audio (e.g. 1 hour), GStreamer buffers could get exhausted, you have to test yourself.

And, if you really have the audio already beforehand, you could use offline recognition (using Kaldi directly) that is probably a bit more accurate and flexible.
